### ISSUE TITLE
Yast2 module for firewalld

### ISSUE THREAD

**Issue by copyme** [yast/yast-firewall#108]
Guys, to be honest `firewall-config` sucks as hell. We need our old yast module for firewall configuration  back, please.

**Comment by jreidinger** [comment]
@copyme we are already working on it. in TW there is already new module, which is of course for now a bit limited as it is completely new code due to differences between technologies.

**Comment by dgdavid** [comment]
Fortunately, [`yast2-firewall` >= 4.0.27 is able to configure firewalld](https://github.com/yast/yast-firewall/blob/192f18d8295ad3917568e56ff9c413739f9e179b/package/yast2-firewall.changes#L53-L63) :tada: :tada:

So, this issue can be closed :)
