### ISSUE TITLE
Feature Question

### ISSUE THREAD

**Issue by mister-man** [yast/yast-firewall#154]
Hello together,

if have a question. Is there an way to get the custom rules from SuseFirewall2 back. Or is there an replacement? (I mean a yast replacement)

Thanks a lot.

**Comment by imobachgs** [comment]
Hi @mister-man,

You might be interested in https://build.opensuse.org/package/show/openSUSE:Factory/susefirewall2-to-firewalld because YaST does not support SuSEfirewall2 anymore.

Regards,
Imo

**Comment by mister-man** [comment]
Sorry for my late answer. I mean in SuSEfirewall2 i can make custom rules for ipx on port n in yast. Is it possible to make such rules in yast2 for firewalld. 

Thanks
